"""empty message

Revision ID: 4744a3a56f55
Revises: 97fd285963c7
Create Date: 2020-01-18 20:10:06.316710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4744a3a56f55'
down_revision = '97fd285963c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('address', sa.String(length=200), nullable=False))
    op.add_column('person', sa.Column('phone', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'person', ['address'])
    op.create_unique_constraint(None, 'person', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'phone')
    op.drop_column('person', 'address')
    # ### end Alembic commands ###
