"""empty message

Revision ID: 97fd285963c7
Revises: 540192f3b71d
Create Date: 2020-01-18 20:07:20.091637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97fd285963c7'
down_revision = '540192f3b71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('full_name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'person', ['full_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'full_name')
    # ### end Alembic commands ###
